apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-db-secret
  namespace: ecommerce
type: Opaque
data:
  # echo -n "admin" | base64
  db-username: YWRtaW4=
  # echo -n "admin123" | base64
  db-password: YWRtaW4xMjM=
  keycloak-admin-username: YWRtaW4=
  keycloak-admin-password: YWRtaW4xMjM=
