quarkus.application.name=payment-service
quarkus.http.port=8088

quarkus.smallrye-openapi.info-title=Payment Service API
quarkus.swagger-ui.always-include=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/payment_db

quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true

quarkus.oidc.auth-server-url=http://localhost:8080/realms/ecommerce
quarkus.oidc.client-id=ecommerce-backend
quarkus.oidc.credentials.secret=ecommerce-backend-secret
quarkus.oidc.application-type=service
quarkus.oidc.roles.role-claim-path=groups

kafka.bootstrap.servers=localhost:29092

# Incoming: stock-reserved
mp.messaging.incoming.stock-reserved-in.connector=smallrye-kafka
mp.messaging.incoming.stock-reserved-in.topic=stock-reserved
mp.messaging.incoming.stock-reserved-in.group.id=payment-service
mp.messaging.incoming.stock-reserved-in.value.deserializer=io.quarkus.kafka.client.serialization.JsonbDeserializer
mp.messaging.incoming.stock-reserved-in.value.type=com.ecommerce.common.event.StockReservedEvent

# Outgoing: payment-processed
mp.messaging.outgoing.payment-processed-out.connector=smallrye-kafka
mp.messaging.outgoing.payment-processed-out.topic=payment-processed
mp.messaging.outgoing.payment-processed-out.value.serializer=io.quarkus.kafka.client.serialization.JsonbSerializer

quarkus.log.level=INFO
quarkus.log.category."com.ecommerce".level=DEBUG
quarkus.http.cors=true
quarkus.http.cors.origins=*
